CONFIG_SENSOR_MODULE=y
CONFIG_SENSOR_MODULE_TEMP=y
CONFIG_SENSOR_MODULE_TEMP_PERIOD=1000
CONFIG_SENSOR_MODULE_TEMP_DELTA_INT=0
# CONFIG_SENSOR_MODULE_HUMID=y
# CONFIG_SENSOR_MODULE_HUMID_PERIOD=70
# CONFIG_SENSOR_MODULE_HUMID_DELTA_INT=0
# CONFIG_SENSOR_MODULE_PRESS=y
# CONFIG_SENSOR_MODULE_PRESS_PERIOD=70
# CONFIG_SENSOR_MODULE_PRESS_DELTA_DEC=0
# CONFIG_SENSOR_MODULE_GAS_RES=y
# CONFIG_SENSOR_MODULE_GAS_RES_PERIOD=70
# CONFIG_SENSOR_MODULE_GAS_RES_DELTA=0
# CONFIG_SENSOR_MODULE_ACCEL=y
# CONFIG_SENSOR_MODULE_ACCEL_PERIOD=70
# CONFIG_SENSOR_MODULE_ACCEL_X_DELTA_INT=0
